spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  neo4j:
    init:
      mode: always
      data-locations: classpath:data.neo4j
