services:
  # -------------------- Containers --------------------

  ps_db:
    env_file:
      - path: ./local.env
        required: false
    image: postgres:latest
    container_name: ps_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ps_db
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5436:5432'
    volumes:
      - ps_db:/var/lib/postgresql/data
    restart: always

  ps_neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugin:/plugins
    restart: always


# ---------- Volumes ----------
volumes:
  ps_db:
    driver: local